### ISSUE TITLE
Installation fails in Observer.php

### ISSUE THREAD

**Issue by winkelsdorf** [TheExtensionLab/StatusColors#6]
Just one quick note: The change in Model/Observer.php, showing the default installation successful message, gives an error.

``` code
$setup = new TheExtensionLab_StatusColors_Model_Resource_Setup;
$setup->addInstallationSuccessfulNotification();
```

fails upon fresh installation (cleaned db) with:

```
Warning: Missing argument 1 for Mage_Core_Model_Resource_Setup::__construct(), called in /Users/winkelsdorf/sites/magento.1910.dev/app/code/community/TheExtensionLab/StatusColors/Model/Observer.php on line 23 and defined  in /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/Resource/Setup.php on line 127

#0 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/Resource/Setup.php(127): mageCoreErrorHandler(2, 'Missing argumen...', '/Users/winkelsd...', 127, Array)
#1 /Users/winkelsdorf/sites/magento.1910.dev/app/code/community/TheExtensionLab/StatusColors/Model/Observer.php(23): Mage_Core_Model_Resource_Setup->__construct()
#2 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/App.php(1338): TheExtensionLab_StatusColors_Model_Observer->adminhtmlBlockHtmlBefore(Object(Varien_Event_Observer))
#3 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod(Object(TheExtensionLab_StatusColors_Model_Observer), 'adminhtmlBlockH...', Object(Varien_Event_Observer))
#4 /Users/winkelsdorf/sites/magento.1910.dev/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('adminhtml_block...', Array)
#5 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Adminhtml/Block/Template.php(80): Mage::dispatchEvent('adminhtml_block...', Array)
#6 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Adminhtml_Block_Template->_toHtml()
#7 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#8 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#9 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#10 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#11 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Adminhtml/controllers/IndexController.php(82): Mage_Core_Controller_Varien_Action->renderLayout()
#12 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_IndexController->loginAction()
#13 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('login')
#14 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#15 /Users/winkelsdorf/sites/magento.1910.dev/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#16 /Users/winkelsdorf/sites/magento.1910.dev/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#17 /Users/winkelsdorf/Sites/magento.1910.dev/index.php(91): Mage::run('', 'store')
#18 {main}
```

Related to latest commit in 340527babe451e2af92958a492af5a8d58378271.

Edit: Probably related to not removing the extension from core_resource table. Working when commenting the mentioned code out.

Cheers,
Frederik

**Comment by JamesAnelay** [comment]
Ahh bugger, sorry @winkelsdorf, the two lines below in Observer.php were suppose to be for my internal testing and not commited.

``` code
$setup = new TheExtensionLab_StatusColors_Model_Resource_Setup;
$setup->addInstallationSuccessfulNotification();
```

I have removed them in the latest commit and you can just do the same locally.

Sorry about that and thanks for the heads up,
- James

**Comment by winkelsdorf** [comment]
Haha, nevermind - working fine of course :) And thanks again!
